phoenixChat/chat/api/urls.py
from django.urls import path
from .views import ChatMessageListView, ChatMessageDetailView

urlpatterns = [
    path('chatMessage/',ChatMessageListView.as_view()),
    path('chatMessage/<pk>/',ChatMessageDetailView.as_view())
]

phoenixChat/chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, InboxView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
]

phoenixChat/phoenixChat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from .views import signup, home, log_in
from django.contrib.auth.views import LoginView as login

app_name = 'chat'
urlpatterns = [
    path(r'login/',log_in, name='login'),
    path('',signup, name='signup'),
    path('home/', home,name='home'),
    path('admin/', admin.site.urls),
    path('messages/', include('chat.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('chat.api.urls')),
]

phoenixChat/chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q

from django.contrib.auth.signals import user_logged_in, user_logged_out  

class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): 
        # get existing thread or create a new one
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

phoenixChat/chat/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

phoenixChat/chat/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView

from chat.models import ChatMessage
from .serializers import ChatMessageSerializer

class ChatMessageListView(ListAPIView):
    queryset = ChatMessage.objects.all()
    serializer_class = ChatMessageSerializer

class ChatMessageDetailView(RetrieveAPIView):
    queryset = ChatMessage.objects.all()
    serializer_class = ChatMessageSerializer

phoenixChat/chat/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.edit import FormMixin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage
from django.contrib.auth.models import User

from django.views import generic
from django.views.generic import View

class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        users = User.objects.values()
        return render(request, 'thread.html', {'users':users})

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

    

phoenixChat/chat/templates/chat/thread.html
{% extends "base.html" %}
{% block content %}
<!-- <ul id='chat-items'> -->
<!-- {% for chat in object.chatmessage_set.all %}

<li>{{ chat.message }} via {{ chat.user }}</li>

{% endfor %} -->
<!-- </ul> -->
<div class="row">

                <div class=" mt-5 chat">
                    <div class="card">
                        <div class="card-header msg_head">
                            <div class="d-flex bd-highlight">
                                <div class="img_cont">
                                    <img src="https://vignette.wikia.nocookie.net/tomandjerry/images/5/5f/JerryMouse.png/revision/latest?cb=20140723114908" class="rounded-circle user_img">
                                    <span class="online_icon"></span>
                                </div>
                                <div class="user_info">
                                    <span>{% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</span>
                                </div>
                                
                            </div>
                            <!-- <span id="action_menu_btn"><i class="fas fa-ellipsis-v"></i></span>
                            <div class="action_menu">
                                <ul>
                                    <li><i class="fas fa-user-circle"></i> View profile</li>
                                    <li><i class="fas fa-users"></i> Add to close friends</li>
                                    <li><i class="fas fa-plus"></i> Add to group</li>
                                    <li><i class="fas fa-ban"></i> Block</li>
                                </ul>
                            </div> -->
                        </div>
                        <div class="card-body msg_card_body" id='chat-itemsss'>
                            {% for chat in object.chatmessage_set.all %}
                                {% if user == chat.user %}
                                    <div class="d-flex justify-content-start mb-4">
                                        <div class="img_cont_msg">
                                            <img src="https://vignette.wikia.nocookie.net/tomandjerry/images/5/5f/JerryMouse.png/revision/latest?cb=20140723114908" class="rounded-circle user_img_msg">
                                        </div>
                                        <div class="msg_cotainer">
                                            {{ chat.message }}
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="d-flex justify-content-end mb-4">
                                        <div class="msg_cotainer_send">
                                            {{ chat.message }}
                                        </div>
                                        <div class="img_cont_msg">
                                            <img src="https://upload.wikimedia.org/wikipedia/en/f/f6/Tom_Tom_and_Jerry.png" class="rounded-circle user_img_msg">
                                        </div>
                                    </div>
                                {% endif %}
                            
                            {% endfor %}
                        </div>
                        <div class="card-footer">
                			<div class="input-group"> 
                				<center>
		                		<form id='form' method='POST'> 
		                		{% csrf_token %}
		                    		<input type="hidden" id="username" value = '{{ user }}' />
		                    		{{form.as_p }}
		                    		<input type='submit' class='send_btn'/>
		                		</form>
		                		</center>
	            			</div>
            			</div>
                </div>
</div>      
</div>          
                {% endblock %}
{% block script %}


<script>
// websocket scripts
// connect backend and frontend to properly communicate with each other
// console.log(window.location)

var ws = 'ws://'
if (window.location.protocol === 'https:'){
    ws = 'wss://'
}
var endpoint = ws + window.location.host + window.location.pathname
// var endpoint = ''
var socket = new WebSocket(endpoint)

var chatHolder = $("#chat-itemsss")
socket.onmessage = function(e){
    console.log("message", e)
    var chatData = JSON.parse(e.data)
    if ($("#username").val() === chatData.username){
	   chatHolder.append(
	   	"<div class='d-flex justify-content-start mb-4'>"+
	   	            "<div class='img_cont_msg'>" +
	   	                "<img src='https://vignette.wikia.nocookie.net/tomandjerry/images/5/5f/JerryMouse.png/revision/latest?cb=20140723114908' class='rounded-circle user_img_msg'>"+
	   	            "</div>"+
	   	            "<div class='msg_cotainer'>" +
	   	                chatData.message + 
	   	            "</div>" +
	   	         "</div>"
	 )
    }
    else{
    	chatHolder.append(
    	"<div class='d-flex justify-content-end mb-4'>"+
	   	            "<div class='msg_cotainer_send'>" +
	   	                chatData.message  +
	   	                "<span class='msg_time_send'>8:40 AM, Today</span>" +
	   	            "</div>" +
	   	            "<div class='img_cont_msg'>" +
	   	                "<img src='https://upload.wikimedia.org/wikipedia/en/f/f6/Tom_Tom_and_Jerry.png' class='rounded-circle user_img_msg'>"+
	   	            "</div>"+
	   	         "</div>"
	   	         )
    }
}
socket.onopen = function(e){
    console.log("open", e)
    var formData = $("#form");
    formData.submit(function(event){
        event.preventDefault();
        // prevents form from being submitted by default if socket is connected
        // default action will still work if socket is not connecting
        var msgData = $("#id_message").val()
        // chatHolder.append("<li> S: " + msgData + " via " + $("#username").val() + "</li>")
        msgText = {
            'message': msgData
        }
        socket.send(JSON.stringify(msgText))
        formData[0].reset()
    })
}
socket.onerror = function(e){
    console.log("error", e)
}
socket.onclose = function(e){
    console.log("close", e)
}
</script>
<script>
    $(document).ready(function(){
        $('#action_menu_btn').click(function(){
            $('.action_menu').toggle();
        });
    });
</script>
<style> body,html{
            height: 100%;
            margin: 0;
            
        }

        .chat{
            margin-top: 4rem;
            margin-bottom: auto;
            margin: auto;
        }
        .card{
            height: 90vh;
            border-radius: 15px !important;
            background-color: rgba(0,0,0,0.4) !important;
        }
        .contacts_body{
            padding:  0.75rem 0 !important;
            overflow-y: auto;
            white-space: nowrap;
        }
        .msg_card_body{
            overflow-y: auto;
        }
        .card-header{
            border-radius: 15px 15px 0 0 !important;
            border-bottom: 0 !important;
        }
     .card-footer{
        border-radius: 0 0 15px 15px !important;
            border-top: 0 !important;
    }
        .container{
            align-content: center;
        }
        .search{
            border-radius: 15px 0 0 15px !important;
            background-color: rgba(0,0,0,0.3) !important;
            border:0 !important;
            color:white !important;
        }
        .search:focus{
             box-shadow:none !important;
           outline:0px !important;
        }
        .type_msg, #id_message{
            background-color: rgba(0,0,0,0.3) !important;
            border:0 !important;
            color:white !important;
            height: 60px !important;
            overflow-y: auto;
            width: 400px;
        }
            .type_msg:focus{
             box-shadow:none !important;
           outline:0px !important;
        }
        .attach_btn{
    border-radius: 15px 0 0 15px !important;
    background-color: rgba(0,0,0,0.3) !important;
            border:0 !important;
            color: white !important;
            cursor: pointer;
        }
        .send_btn{
   			 border-radius: 15px !important;
    		background-color: rgba(0,0,0,0.3) !important;
            border:0 !important;
            color: white !important;
            cursor: pointer;
            padding: 5px 50px;
        }
        .search_btn{
            border-radius: 0 15px 15px 0 !important;
            background-color: rgba(0,0,0,0.3) !important;
            border:0 !important;
            color: white !important;
            cursor: pointer;
        }
        .contacts{
            list-style: none;
            padding: 0;
        }
        .contacts li{
            width: 100% !important;
            padding: 5px 10px;
            margin-bottom: 15px !important;
        }
    .active{
            background-color: rgba(0,0,0,0.3);
    }
        .user_img{
            height: 70px;
            width: 70px;
            border:1.5px solid #f5f6fa;
        
        }
        .user_img_msg{
            height: 40px;
            width: 40px;
            border:1.5px solid #f5f6fa;
        
        }
    .img_cont{
            position: relative;
            height: 70px;
            width: 70px;
    }
    .img_cont_msg{
            height: 40px;
            width: 40px;
    }
    .online_icon{
        position: absolute;
        height: 15px;
        width:15px;
        background-color: #4cd137;
        border-radius: 50%;
        bottom: 0.2em;
        right: 0.4em;
        border:1.5px solid white;
    }
    .offline{
        background-color: #c23616 !important;
    }
    .user_info{
        margin-top: auto;
        margin-bottom: auto;
        margin-left: 15px;
    }
    .user_info span{
        font-size: 20px;
        color: white;
    }
    .user_info p{
    font-size: 10px;
    color: rgba(255,255,255,0.6);
    }
    .video_cam{
        margin-left: 50px;
        margin-top: 5px;
    }
    .video_cam span{
        color: white;
        font-size: 20px;
        cursor: pointer;
        margin-right: 20px;
    }
    .msg_cotainer{
        margin-top: auto;
        margin-bottom: auto;
        margin-left: 10px;
        border-radius: 25px;
        background-color: #82ccdd;
        padding: 10px;
        position: relative;
    }
    .msg_cotainer_send{
        margin-top: auto;
        margin-bottom: auto;
        margin-right: 10px;
        border-radius: 25px;
        background-color: #78e08f;
        padding: 10px;
        position: relative;
    }
    .msg_time{
        position: absolute;
        left: 0;
        bottom: -15px;
        color: rgba(255,255,255,0.5);
        font-size: 10px;
    }
    .msg_time_send{
        position: absolute;
        right:0;
        bottom: -15px;
        color: rgba(255,255,255,0.5);
        font-size: 10px;
    }
    .msg_head{
        position: relative;
    }
    #action_menu_btn{
        position: absolute;
        right: 10px;
        top: 10px;
        color: white;
        cursor: pointer;
        font-size: 20px;
    }
    .action_menu{
        z-index: 1;
        position: absolute;
        padding: 15px 0;
        background-color: rgba(0,0,0,0.5);
        color: white;
        border-radius: 15px;
        top: 30px;
        right: 15px;
        display: none;
    }
    .action_menu ul{
        list-style: none;
        padding: 0;
    margin: 0;
    }
    .action_menu ul li{
        width: 100%;
        padding: 10px 15px;
        margin-bottom: 5px;
    }
    .action_menu ul li i{
        padding-right: 10px;
    
    }
    .action_menu ul li:hover{
        cursor: pointer;
        background-color: rgba(0,0,0,0.2);
    }
    @media(max-width: 576px){
    .contacts_card{
        margin-bottom: 15px !important;
    }
    }</style>
{% endblock %}